## Two dimensional tensors

In [1]:
import torch

In [2]:
a = [[11,12,13],[21,22,23],[31,32,33]]

In [3]:
A = torch.tensor(a)

In [4]:
A

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [6]:
#get dimension
A.ndim

2

In [7]:
A.shape #get rows and columns

torch.Size([3, 3])

In [10]:
A.size() 

torch.Size([3, 3])

### INdexing and SLicing

In [13]:
#get all rows of first columns
A[:,1]

tensor([12, 22, 32])

In [17]:
#get element of first row and first column
A[0,0]

tensor(11)

In [18]:
A[1][2] #second row third columns

tensor(23)

In [23]:
#slicing
A[0,0:2] #first row and first , second columns.

tensor([11, 12])

In [24]:
A[1:3,2] #second and third row , third column

tensor([23, 33])

## Basic operations in 2d

In [26]:
x = torch.tensor([[1,0] , [0,1]])

In [27]:
y = torch.tensor([[2,1] , [1,2]])

In [28]:
z = x+y

In [29]:
z

tensor([[3, 1],
        [1, 3]])

In [30]:
#multiply
y

tensor([[2, 1],
        [1, 2]])

In [32]:
z = 2*y

In [33]:
z

tensor([[4, 2],
        [2, 4]])

In [34]:
#elements wise product
x

tensor([[1, 0],
        [0, 1]])

In [35]:
y

tensor([[2, 1],
        [1, 2]])

In [36]:
z = x*y

In [37]:
z

tensor([[2, 0],
        [0, 2]])

In [58]:
#matrix multiplication
a = torch.tensor([[0,1,1] , [1,0,1]])

In [44]:
a

tensor([[0, 1, 1],
        [1, 0, 1]])

In [53]:
b = torch.tensor([[1],[1],[1]])
b

tensor([[1],
        [1],
        [1]])

In [56]:
z = torch.mm(a,b)

In [57]:
z

tensor([[2],
        [2]])